<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishTrimmed>false</PublishTrimmed>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CUE4Parse" Version="1.2.2.202608" />
    <PackageReference Include="CUE4Parse-Conversion" Version="1.2.2.202608" />
    <PackageReference Include="EpicManifestParser" Version="3.0.0-preview.1" />
  </ItemGroup>
</Project>
